### ISSUE TITLE
Fix issues with results from r20200714

### ISSUE THREAD

**Issue by jcohenadad** [spine-generic/data-single-subject#4]
A new release of results was published here: https://github.com/spine-generic/data-single-subject/releases/tag/r20200714

It contains a few issues (e.g. inconsistent values, etc.) that will be listed here for the record.

**Comment by valosekj** [comment]
So far, I have found following issues:
- [x] `sub-douglas` - MT input data are missing - probably already known because subject is not listed in MT figures 
- [ ]  `sub-juntendoAchieva` - GM CSA was not computed successfully - when I checked raw anat data using fsleyes, I could see that T2star is absolutely not aligned with T1w image. This probably resulted into bad PAM50_levels --> T2star registration and impossibility to compute GM CSA.
- [ ] `sub-perform` - low value of FA - raw DWI data are corrupted by aliasing artifacts 
- [ ] `sub-glen` - low value of MD and RD - raw DWI data look atypically - i.) b0 volume looks similar as b=800 volumes, ii.) one slice in almost all volumes looks like be acquired without diff. weighting

**Comment by jcohenadad** [comment]
> MT input data are missing - probably already known because subject is not listed in MT figures

indeed, i already know it.

> sub-juntendoAchieva - GM CSA was not computed successfully - when I checked raw anat data using fsleyes, I could see that T2star is absolutely not aligned with T1w image. This probably resulted into bad PAM50_levels --> T2star registration and impossibility to compute GM CSA.

thanks! that's helpful. I'll look at the processed data.

> sub-perform - low value of FA - raw DWI data are corrupted by aliasing artifacts

indeed, that's life 😞   we will report it in the article.

> sub-glen - low value of MD and RD - raw DWI data look atypically - i.) b0 volume looks similar as b=800 volumes, ii.) one slice in almost all volumes looks like be acquired without diff. weighting

that's helpful, thanks. I'll look at the processed data.

**Comment by jcohenadad** [comment]
Addressed in spine-generic/data-single-subject_DO-NOT-USE#11
